# **Numpy**

Numpy is a powerful Python library for numerical computations. It offers multi-dimensional arrays, mathematical functions, and efficient operations. It's used in data analysis, machine learning, and scientific computing.

#### Why use Numpy?

- It is easy to learn.
- It is easy to use.
- It uses relatively less memory to store data.
- It provides efficient storage.
- Do complex math.
- Broad range of mathematical functions.

### ***Importing Numpy***

In [5]:
import numpy as np

##### **1-D Array**

In [7]:
arr1 = np.array([10, 12, 15, 21])

In [8]:
arr1

array([10, 12, 15, 21])

In [164]:
arr1[0]

10

##### **2-D Array**

In [11]:
arr2 = np.array([[10, 72, 12, 33]])

In [12]:
arr2

array([[10, 72, 12, 33]])

In [13]:
arr2[0,1]

72

### Attributes and Methods in Numpy

- **Attributes :** Attributes are properties or characteristics of a Numpy array. They provide information about the array's dimensions, data type, shape, and more.
***ie.. shape, size, dtype, ndim, flags, etc..***

- **Methods :** Methods are functions associated with Numpy arrays that allow you to perform various operations on the array data.
***ie.. reshape(), resize(), sum(), ravel(), tolist(), etc...***

***shape - Return the shape of an array***

In [14]:
arr2.shape

(1, 4)

***dtype - Return the data type of elements within a Numpy array.***

In [15]:
arr2.dtype

dtype('int32')

In [16]:
arr2[0,1] = 40

In [17]:
arr2

array([[10, 40, 12, 33]])

In [19]:
arr3 = np.array([[62,12,22], [32,19,28], [11,38,26]])

In [20]:
arr3

array([[62, 12, 22],
       [32, 19, 28],
       [11, 38, 26]])

In [21]:
arr3.shape

(3, 3)

***size- Return the total number of elements in the array.***

In [22]:
arr3.size

9

## Array Creation

**Create an array, each element of which is zero.**

In [24]:
zeros = np.zeros((3,3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Create an array, each element of which is one.**

In [26]:
ones = np.ones((2,5))

In [27]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Create a Numpy array, containing the integers from 0 to n.**

In [28]:
range = np.arange(10)

In [29]:
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Create an array of evenly space values.**

In [30]:
lspace = np.linspace(1,40,6)

In [31]:
lspace

array([ 1. ,  8.8, 16.6, 24.4, 32.2, 40. ])

**Create an array of a specified shape but the value will be arbitrary.**

In [32]:
emp = np.empty((4,3))

In [33]:
emp

array([[1.35931428e-311, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 1.03977794e-312, 1.31370903e-076],
       [4.97788705e-091, 2.32002835e-056, 1.52516742e-052],
       [3.14379749e+179, 3.99910963e+252, 1.90979636e-312]])

**Create a new array with the same shape, data type as an existing array.**

In [34]:
emp_like = np.empty_like(arr3)

In [35]:
emp_like

array([[          0,           0, -1787981648],
       [        640, -1787983088,         640],
       [-1787981088,         640,     7077989]])

**Create an identity matrix.**

*An identity matrix is a square matrix with 1's on the diagonal and 0's everywhere else.*

In [36]:
ide = np.identity(10)

In [37]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

***reshape() : Give a new shape to an array without changing its data.***

In [38]:
arr4 = np.arange(33)

In [39]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [40]:
arr4.reshape(3,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

***ravel() : Return the flattend array.***

In [41]:
arr4 = arr4.ravel()

In [42]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

## Numpy Axis

An axis refers to a dimension of a multi-dimensional array. For eaxample, a 2D array has two axes: the first axis (axis 0) represents the rows and the second axis (axis 1) represents the columns.

In [44]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [45]:
arr5 = np.array(x)

In [46]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Axis Operations

***sum() : Sum of array elements over a given axis.***

In [47]:
arr5.sum(axis=0)

array([12, 15, 18])

In [48]:
arr5.sum(axis=1)

array([ 6, 15, 24])

***T : It is a shorthand for the transpose() method. It is used to transpose the array, which means swapping its rows and columns.***

In [49]:
arr5.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

***flat : Return a copy of the array collapsed into one dimension.***

In [50]:
arr5.flat

In [51]:
for item in arr5.flat:
    print(item)

1
2
3
4
5
6
7
8
9


***ndim : Return the number of dimensions of the array.***

In [52]:
arr5.ndim

2

In [53]:
arr5.size

9

***nbytes : It returns the total number of bytes occupied by the array's elements.***

In [54]:
arr5.nbytes

36

In [232]:
arr6 = np.array([[23,61,26], [64,72,29], [17,83,56]])

In [234]:
arr6

array([[23, 61, 26],
       [64, 72, 29],
       [17, 83, 56]])

***argmax() : Retuen the indices of the maximum values along an axis.***

In [240]:
arr6.argmax(axis=0)

array([1, 2, 2], dtype=int64)

In [249]:
arr6.argmax(axis=1)

array([1, 1, 1], dtype=int64)

***argmin() : Return the indices of the minimum values along an axis.***

In [242]:
arr6.argmin(axis=0)

array([2, 0, 0], dtype=int64)

In [244]:
arr6.argmin(axis=1)

array([0, 2, 0], dtype=int64)

***argsort() : Return the indices that would sort an array.***

In [246]:
arr6.argsort(axis=1)

array([[0, 2, 1],
       [2, 0, 1],
       [0, 2, 1]], dtype=int64)

### Mathematical Operations 

#### **Arithmetic Operations**

In [266]:
ar1 = np.array([[1,3,2], [8,2,2], [4,5,6]])

In [268]:
ar1

array([[1, 3, 2],
       [8, 2, 2],
       [4, 5, 6]])

In [270]:
ar2 = np.array([[6,3,2], [1,2,4], [4,1,2]])

In [272]:
ar2

array([[6, 3, 2],
       [1, 2, 4],
       [4, 1, 2]])

***Addition***

In [274]:
ar1 + ar2

array([[7, 6, 4],
       [9, 4, 6],
       [8, 6, 8]])

***Subtraction***

In [276]:
ar1 - ar2

array([[-5,  0,  0],
       [ 7,  0, -2],
       [ 0,  4,  4]])

***Multiplication***

In [278]:
ar1 * ar2

array([[ 6,  9,  4],
       [ 8,  4,  8],
       [16,  5, 12]])

***Division***

In [280]:
ar1 / ar2

array([[0.16666667, 1.        , 1.        ],
       [8.        , 1.        , 0.5       ],
       [1.        , 5.        , 3.        ]])

***Floor Division***

In [286]:
ar1 // ar2

array([[0, 1, 1],
       [8, 1, 0],
       [1, 5, 3]])

***Modulus***

In [289]:
ar1 % ar2

array([[1, 0, 0],
       [0, 0, 2],
       [0, 0, 0]])

***Exponentiation***

In [292]:
ar1 ** ar2

array([[  1,  27,   4],
       [  8,   4,  16],
       [256,   5,  36]])

***sqrt() : It is a function used to calculate the square root of each element in a Numpy array.***

In [79]:
np.sqrt(ar1)

array([[1.        , 1.73205081, 1.41421356],
       [2.82842712, 1.41421356, 0.        ],
       [2.        , 2.23606798, 2.44948974]])

In [80]:
ar2.sum()

18

***where() : It is a versetile function that returns the indices of elements in an array that meet a certain condition.***

In [81]:
k = np.array([[4,5,0], [6,0,3], [1,6,5]])

In [82]:
k

array([[4, 5, 0],
       [6, 0, 3],
       [1, 6, 5]])

In [83]:
np.where(k>5)

(array([1, 2], dtype=int64), array([0, 1], dtype=int64))

***count_nonzero() : It is a funtion that count the number of non-zero elements in an array.***

In [84]:
np.count_nonzero(k)

7